### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by leonardomarciano** [Bensigo/bitcoin-payment-microservice#3]
There is a problem with getUnspentUtxos in sendBTC Function: it returns an empty object

```
450
amt: 39999550
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at insight.getUnspentUtxos (C:\Users\loleo\Projetos\Gateway\node_modules\bitcoin-payment-microservice\src\index.js:80:27)
    at Request._callback (C:\Users\loleo\Projetos\Gateway\node_modules\bitcore-explorers\lib\insight.js:80:12)
    at Request.self.callback (C:\Users\loleo\Projetos\Gateway\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\loleo\Projetos\Gateway\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\loleo\Projetos\Gateway\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by musafarouk** [comment]
Can i see the code you used?
